### PR TITLE
Update to TeX Live 2021

### PR DESCRIPTION
**Pull request by vlasakm**
So, I tried my hand at updating to TeX Live 2021. As it turns out, this is over my head, and I am not able to fully finish it alone.

I added some preparations for TeX Live 2022, because I know about them and it seemed nice to have a notice for next time.

Where things don't work /  I got stuck:

1) stage3: IIRC I couldn't get the normal `run.sh` script to work properly. `run-build` step failed, but running it again seemed to proceed just fine. Maybe some missing dependencies in build order?
2) stage4: I got errors from `splitup` that indicated a fail after `@define procedure getmd5sum();` in `xetex.defines`.
3) stage2: After trying from scratch, I couldn't even get past stage2 (hence my incomplete descriptions of stages 3 and 4). The build errors out with error like the below one, for pretty much all `xetex*` files:

```
[1/9] CC xetex_xetex-pool.o
FAILED: xetex_xetex-pool.o
gcc -c -o xetex_xetex-pool.o -MT xetex_xetex-pool.o -MD -MP -MF xetex_xetex-pool.o.d -DHAVE_CONFIG_H -D__SyncTeX__ -I. -I../xetexdir -I.. -I../libmd5 -I../pplib -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O0 xetex-pool.c
In file included from /usr/include/math.h:37,
                 from ../kpathsea/c-std.h:28,
                 from ../kpathsea/config.h:88,
                 from ../w2c/config.h:23,
                 from ../xetexdir/cpascal.h:16,
                 from ../xetexdir/texmfmp.h:5,
                 from xetexd.h:89,
                 from xetex-pool.c:7:
/usr/include/x86_64-linux-gnu/bits/types.h:31:1: error: expected identifier or '(' before 'typedef'
   31 | typedef unsigned char __u_char;
      | ^~~~~~~
In file included from ../kpathsea/systypes.h:22,
                 from ../kpathsea/c-unistd.h:24,
                 from ../kpathsea/c-std.h:38,
                 from ../kpathsea/config.h:88,
                 from ../w2c/config.h:23,
                 from ../xetexdir/cpascal.h:16,
                 from ../xetexdir/texmfmp.h:5,
                 from xetexd.h:89,
                 from xetex-pool.c:7:
/usr/include/x86_64-linux-gnu/sys/types.h:33:9: error: unknown type name '__u_char'
   33 | typedef __u_char u_char;
      |         ^~~~~~~~
```

### CODE REVIEW

**Comment by vlasakm** [comment]
Sorry for not getting further with this, as I didn't have that much time to get further. I am glad that it atleast gave you a rough head start. I also just now noticed that I omitted important information in my original PR message - like the SVN revision number / git tag. Retroactively `git add -p` makes a lot of sense, since it is clear for my commit history that I kind of understimated the process. So sorry about all that.

I will now try to run through the process to check the `reference-sources` and will get back to you.

**Comment by vlasakm** [comment]
I probably won't have a chance to incorporate the reference sources diffs into the main repo in the near future.

At least I tried to independently run your validation script:

```
Success! Everything is self-consistent.
```

So everything seems good.

**Comment by fyemath** [comment]
May I ask, what is the url for the bundle of TeXLive 2021?

**Comment by vlasakm** [comment]
There is no TeXLive 2021 bundle, yet.

Beware that the update concerns three repositories, each with different purposes, which should hopefully become clear in a minute.

 - https://github.com/tectonic-typesetting/tectonic-texlive-bundles (scripts for building bundles from TL, i.e. the stuff that ultimately comes from CTAN)
 - https://github.com/tectonic-typesetting/tectonic-staging (scripts for extracting engine reference sources from TL, i.e. the stuff that comes from "XeTeX developers")
 - https://github.com/tectonic-typesetting/tectonic (which points to a default bundle and has forked XeTeX sources which have to be updated)

AFAIK, tectonic updates to new TeXLive releases has these stages:

1) The "reference" XeTeX engine sources in the https://github.com/tectonic-typesetting/tectonic-staging repository need to be updated. Done by this PR.
2) The year's worth of changes in the "reference" sources need to manually be applied to the tectonic XeTeX fork (which is split up into several crates in the `creates subdirectory` of https://github.com/tectonic-typesetting/tectonic. This is the next step. When this is done, the git submodule "reference-sources" in https://github.com/tectonic-typesetting/tectonic will also be updated to reflect that tectonic conforms to the newer reference sources.
3) After the XeTeX engine is updated, then the bundles can be created. This work should happen in the https://github.com/tectonic-typesetting/tectonic-texlive-bundles repository. This is hopefully fairly easy, since it's scripted and documented. It might be possible to do this before 2), but 2) still blocks next progress.
4) The default bundle of tectonic is changed to point to this new bundle.
5) New tectonic version is released.

So what you are asking for, is the creation of a new bundle for TeX Live 2021. You can start by filing an issue here: https://github.com/tectonic-typesetting/tectonic-texlive-bundles/issues. I am sure that @pkgw would appreciate any contributions towards this. But note that this involves cloning the TeX Live git mirror (~40 GiB).

**Comment by fyemath** [comment]
Thank you very much for the prompt reply! I did know that it would take an effort to update the bundle to 2021. The reason that I would like to use TeXLive 2021 is because there are some new packages and classes in the 2021 collection. I will download missing packages and classes for now. Thank you for your effort towards creating an engine for reproducible documents.

**Comment by pkgw** [comment]
The summary by @vlasakm is spot-on (thanks!). It looks like the update of the main Tectonic implementation to TL2021 will be *relatively* straightforward, but it is always a substantial effort that requires very focused attention, and that's something I don't have much of these days :confused: Once that's done, the update of the bundle is a little tedious but comparatively easy.

**Pull request merged**
